name = "elderflow-lrp"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./apps/web/dist"

[[d1_databases]]
binding = "DB"
database_name = "lrp-database"
database_id = "2f4d6183-d207-4ef9-915c-8ce0cd9bf36e"
migrations_dir = "./apps/web/migrations"
