// @ts-expect-error - virtual module generated by vite-plugin-pwa
import type { RegisterSWOptions } from 'virtual:pwa-register';
// @ts-expect-error - virtual module generated by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register';

type BackgroundSyncRegistration = ServiceWorkerRegistration & {
  sync: {
    register: (tag: string) => Promise<void>;
  };
};

function hasBackgroundSync(registration: ServiceWorkerRegistration): registration is BackgroundSyncRegistration {
  return 'sync' in registration;
}

function triggerBrowserBackgroundSync() {
  if (typeof window === 'undefined') {
    return;
  }

  if (!('serviceWorker' in navigator) || !('SyncManager' in window)) {
    return;
  }

  void navigator.serviceWorker.ready
    .then((registration) => {
      if (!hasBackgroundSync(registration)) {
        return;
      }

      return registration.sync.register('lrp-sync-now');
    })
    .catch(() => undefined);
}

function setupBackgroundSyncBridge() {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
    return;
  }

  navigator.serviceWorker.addEventListener('message', (event) => {
    if (event.data?.type !== 'LRP_BG_SYNC') {
      return;
    }

    import('@/utils/syncEngine')
      .then(({ triggerSyncNow }) => triggerSyncNow())
      .catch(() => undefined);
  });

  window.addEventListener('online', () => {
    triggerBrowserBackgroundSync();
  });
}

export function registerPWA(options: RegisterSWOptions = {}) {
  const updateSW = registerSW({
    onNeedRefresh() {
      if (confirm('有新版本可用，是否立即更新？')) {
        void updateSW(true);
      }
    },
    onOfflineReady() {
      console.log('App ready to work offline');
    },
    onRegistered(registration: ServiceWorkerRegistration | undefined) {
      console.log('SW Registered');
      setupBackgroundSyncBridge();

      if ('SyncManager' in window && registration && hasBackgroundSync(registration)) {
        void registration.sync.register('lrp-sync-now').catch(() => undefined);
      }
    },
    onRegisterError(_error: unknown) {
      console.log('SW registration error');
    },
    ...options,
  });

  return updateSW;
}
