// @ts-expect-error - virtual module generated by vite-plugin-pwa
import type { RegisterSWOptions } from 'virtual:pwa-register';
// @ts-expect-error - virtual module generated by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register';

export function registerPWA(options: RegisterSWOptions = {}) {
  registerSW({
    onNeedRefresh() {
      if (confirm('有新版本可用，是否立即更新？')) {
        // The registerSW function doesn't return an update function in this version
        window.location.reload();
      }
    },
    onOfflineReady() {
      console.log('App ready to work offline');
    },
    onRegistered(_r: unknown) {
      console.log('SW Registered');
    },
    onRegisterError(_error: unknown) {
      console.log('SW registration error');
    },
    ...options,
  });
}